version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mycoin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/mycoin?sslmode=disable
      PORT: 8080
      JWT_SECRET: your-secret-key
    depends_on:
      - postgres
    volumes:
      - .:/app
    working_dir: /app

volumes:
  postgres_data:
